name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build and Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ğŸ¤ª Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: ğŸ’ª Build
        run: go build yoecwid-cli

      - name: ğŸ¤“ Test
        run: go test yoecwid-cli
